public class AddApex {
    public static Integer add(integer a,integer b){
      return a+b;
    }
       /* integer sum = a+b;

            system.debug('Addition = '+sum);
    }
    
    public static void sub(){
        integer a=10,b=2;
        integer sub = a-b;
         system.debug('Subtaction = '+sub);
    }
    
    public static void mul(){
        integer a=10,b=2;
        integer mul = a*b;
         system.debug('multiplication = '+mul);
    }
    
    public static void div(){
        integer a=10,b=2;
        integer div = a/b;
         system.debug('Divide = '+div);
    }*/
    

}